**Thermodynamics correlations for pure components** 



En esta sección se presenta la clase *Thermodynamics_correlations* la cual es usada para calcular 13 propiedades termodinámicas de sustancias puras en función de la temperatura.

Se sigue la siguente convención para presentar identificar las propiedades termodinámicas

property thermodynamics = name property, units, correlation, equation

The thermodynamic correlations are:

-**Solid_Density** = "Solid Density", "[kmol/m^3]", "A+B*T+C*T^2+D*T^3+E*T^4", 0

-**Liquid_Density** = "Liquid Density", "[kmol/m^3]", "A/B^(1+(1-T/C)^D)", 1

-**Vapour_Pressure** = "Vapour Pressure", "[Bar]", "exp(A+B/T+C*ln(T)+D*T^E) * 1e-5", 2

-**Heat_of_Vaporization** = "Heat of Vaporization", "[J/kmol]", "A*(1-Tr)^(B+C*Tr+D*Tr^2)", 3

-**Solid_Heat_Capacity** = "Solid Heat Capacity", "[J/(kmol*K)]", "A+B*T+C*T^2+D*T^3+E*T^4", 4

-**Liquid_Heat_Capacity** = "Liquid Heat Capacity", "[J/(kmol*K)]", "A^2/(1-Tr)+B-2*A*C*(1-Tr)-A*D*(1-Tr)^2-C^2*(1-Tr)^3/3-C*D*(1-Tr)^4/2-D^2*(1-Tr)^5/5", 5

-**Ideal_Gas_Heat_Capacity** = "Ideal Gas Heat Capacity" "[J/(kmol*K)]", "A+B*(C/T/sinh(C/T))^2+D*(E/T/cosh(E/T))^2", 6

-**Second_Virial_Coefficient** = "Second	Virial	Coefficient", "[m^3/kmol]", "A+B/T+C/T^3+D/T^8+E/T^9", 7

-**Liquid_Viscosity** = "Liquid	Viscosity", "[kg/(m*s)]", "exp(A+B/T+C*ln(T)+D*T^E)", 8

-**Vapour_Viscosity** = "Vapour	Viscosity", "[kg/(m*s)]", "A*T^B/(1+C/T+D/T^2)", 9

-**Liquid_Thermal_Conductivity** = "Liquid Thermal Conductivity", "[J/(m*s*K)]", "A+B*T+C*T^2+D*T^3+E*T^4", 10

-**Vapour_Thermal_Conductivity** = "Vapour Thermal Conductivity", "[J/(m*s*K)]", "A*T^B/(1+C/T+D/T^2)", 11

-**Surface_Tension** = "Surface Tension", "[kg/s^2]", "A*(1-Tr)^(B+C*Tr+D*Tr^2)", 12	

In [1]:
import numpy as np
import pandas as pd
import pyther as pt
%matplotlib inline


In [2]:
dppr_file = "PureFull_mod_properties.xls"

thermodynamic_correlations = pt.Thermodynamic_correlations(dppr_file)

component = ['METHANE']

Vapour_Pressure = thermodynamic_correlations.property_cal(component, "Vapour_Pressure")

print(Vapour_Pressure)



              A       B       C           D  E T Min [K] T Max [K]
METHANE  39.205 -1324.4 -3.4366  3.1019e-05  2     90.69    190.56
1 ['METHANE']
sss =  [39.205] [90.69] <class 'numpy.ndarray'>
number of components view temperature =  1 ['METHANE'] None
one component without temperature especific
temperature =  [array([90.69], dtype=object) array([91.69], dtype=object)
 array([92.69], dtype=object) array([93.69], dtype=object)
 array([94.69], dtype=object) array([95.69], dtype=object)
 array([96.69], dtype=object) array([97.69], dtype=object)
 array([98.69], dtype=object) array([99.69], dtype=object)
 array([100.69], dtype=object) array([101.69], dtype=object)
 array([102.69], dtype=object) array([103.69], dtype=object)
 array([104.69], dtype=object) array([105.69], dtype=object)
 array([106.69], dtype=object) array([107.69], dtype=object)
 array([108.69], dtype=object) array([109.69], dtype=object)
 array([110.69], dtype=object) array([111.69], dtype=object)
 array([112.69], dtype=o

In [ ]:
dppr_file = "PureFull_mod_properties.xls"

thermodynamic_correlations = pt.Thermodynamic_correlations(dppr_file)

component = 'METHANE'

temperature = 180.4

property_thermodynamics = thermodynamic_correlations.property_cal(component, "Vapour_Pressure", temperature)

print(property_thermodynamics)



In [ ]:
dppr_file = "PureFull_mod_properties.xls"

thermodynamic_correlations = pt.Thermodynamic_correlations(dppr_file)

component = 'METHANE'

temperature = [180.4, 181.4, 185.3, 210, 85]

property_thermodynamics = thermodynamic_correlations.property_cal(component, "Vapour_Pressure", temperature)

print(property_thermodynamics)



In [ ]:
dppr_file = "PureFull_mod_properties.xls"

thermodynamic_correlations = pt.Thermodynamic_correlations(dppr_file)

component = 'METHANE'

liquid_density = thermodynamic_correlations.property_cal(component, "Liquid_Density")
units = thermodynamic_correlations.units
temperature = thermodynamic_correlations.temperature

print("Liquid_Density = {0} {1}".format(liquid_density, units))
print(temperature)



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
fig, axes = plt.subplots(1, 3, figsize=(10, 4))
x = np.arange(0, 5, 0.25)
axes[0].plot(temperature, liquid_density)
axes[0].set_title("liquid_density")

In [ ]:
dppr_file = "PureFull_mod_properties.xls"

thermodynamic_correlations = pt.Thermodynamic_correlations(dppr_file)

component = 'METHANE'
#component = "ETHANE"
#component = "3-METHYLHEPTANE"
#component = "n-PENTACOSANE"
#component = "ISOBUTANE"
#component = "n-TETRADECANE"

temp = [180.4, 181.4, 185.3, 210, 85]
#temp = 180.4

#property_thermodynamics = thermodynamic_correlations.property_cal(component, Vapour_Pressure, temp)
#property_thermodynamics = property_cal(components, Vapour_Pressure, temp)
#property_thermodynamics = property_cal(component, Vapour_Pressure, [180.4, 181.4, 185.3, 210, 85])
property_thermodynamics = thermodynamic_correlations.property_cal(component, "Vapour_Pressure")

print(property_thermodynamics)

